---
name: Publish container image
on:
  push:
  pull_request:
jobs:
  push_to_registry:
    name: Push container image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build and push container image
        uses: docker/build-push-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: getpatchwork/pyenv
          tags: latest
