---
name: Publish container image
on:
  push:
  pull_request:
jobs:
  push_to_registry:
    name: Push container image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: getpatchwork/pyenv:latest
